- pages/clubs/[id].tsx
> サークル新歓動画二つ目 (#87)

- .eslintrc.js
- .gitignore
- README.md
- apollo.config.js
- components/Banners.tsx
- package-lock.json
- package.json
- pages/about.tsx
- pages/clubs/[id].tsx
- pages/clubs/index.tsx
- pages/graduates/[slug].tsx
- pages/graduates/index.tsx
- pages/index.tsx
- pages/news/[slug].tsx
- pages/news/index.tsx
- pages/static/[slug].tsx
- scripts/prebuild/index.ts
- scripts/prebuild/staticData.ts
- scripts/tsconfig.json
- utils/apollo.ts
> バナーを表示できるようにする

- pages/graduates/[slug].tsx
> OBOG記事要約部分 (#66)

- pages/clubs/[id].tsx
> サークル画像複数表示ミス直し (#59)

- pages/graduates/[slug].tsx
> OBOG記事ヒーローヘッダー (#102)

- pages/static/[slug].tsx
> 固定ページヒーローヘッダー (#100)

- pages/companies/[slug].tsx
> 企業詳細ページの作成

- pages/clubs/[id].tsx
> サークル詳細ページに構成員数を追加

- pages/graduates/[slug].tsx
> 卒業生インタビュー詳細ページでStructured Textをサポート

- components/ArticleContentContainer.tsx
- components/Footer.tsx
- pages/about.tsx
- pages/clubs/[id].tsx
- pages/companies/[slug].tsx
- pages/events/[slug].tsx
- pages/graduates/[slug].tsx
- pages/internships/[slug].tsx
- pages/news/[slug].tsx
- pages/static/[slug].tsx
> 記事コンテンツの横幅とパディングを共通化

- components/ArticleContentStructuredTextRenderer/CallToActionButton.tsx
- components/ArticleContentStructuredTextRenderer/PersonAndStatement.tsx
- components/ArticleContentStructuredTextRenderer/index.tsx
- pages/companies/[slug].tsx
- pages/graduates/[slug].tsx
- pages/static/[slug].tsx
> Structured TextにCallToActionButtonを追加 (#145)

- components/HighlightedArticleLink.tsx
- pages/clubs/index.tsx
- pages/graduates/index.tsx
> 卒業生インタビューとサークルのPICK UP部分の画像のアスペクト比を固定

- pages/events/[slug].tsx
- pages/internships/[slug].tsx
> インターンとイベントから代表者、設立年消去 (#170)

- .dockerignore
- preview/Caddyfile
- preview/Dockerfile
- render.yaml
最近話題のPaaSの[Render](https://render.com/)を使って実装してみた。
* Node: 7USD/month
* Caddy (Basic認証のために用意した): 7USD/month
closes #61 
closes #169
> プレビュー機能の実装

- pages/internships/[slug].tsx
> インターンシップ詳細に企業詳細を追加

- pages/events/[slug].tsx
> イベント詳細ページにタイムスケジュール追加

- pages/graduates/index.tsx
> 卒業生インタビューのカテゴリの階層を1段に

- components/ArticleContentStructuredTextRenderer/ArticleGallery.tsx
- pages/graduates/index.tsx
> ArticleLinkで様々な記事タイプをサポートするようにした

- pages/companies/[slug].tsx
> 企業詳細からイベントページへのリンクの修復

- components/ArticleContentStructuredTextRenderer/ArticleGallery.tsx
> ArticleGalleryのリンク修正

- pages/career-strategies/index.tsx
> キャリア戦略論ホームに導入文設置

- pages/internships/[slug].tsx
> インターンシップ詳細を常に表示

- components/ArticleContentStructuredTextRenderer/ArticleLink.tsx
- components/ArticleContentStructuredTextRenderer/EmbeddedImage.tsx
- components/Banners.tsx
- components/Carousel.tsx
- components/HighlightedArticleLink.tsx
- components/ResponsiveImageWithFallback.tsx
- pages/clubs/[id].tsx
- pages/clubs/index.tsx
- pages/companies/[slug].tsx
- pages/events/[slug].tsx
- pages/events/index.tsx
- pages/graduates/index.tsx
- pages/index.tsx
- pages/internships/[slug].tsx
> 積極的な画像最適化・遅延読み込みの際のアニメーション削減

- components/Layout.tsx
- pages/index.tsx
> トップページにdescriptionメタデータタグを追加

- pages/index.tsx
> TOP赤門画面の縦幅を小さくする

- pages/graduates/index.tsx
> 卒業生インタビューの検索画面での画像のアスペクト比を4:3に固定する

- pages/clubs/index.tsx
- pages/index.tsx
> トップページのタイトル変更

- pages/clubs/index.tsx
- pages/companies/index.tsx
- pages/events/index.tsx
- pages/industries/index.tsx
- pages/internships/index.tsx
> getStaticPropsを使用しているページでrevalidateさせる

- pages/career-strategies/index.tsx
> キャリア戦略一覧ページの行間調整

- next-env.d.ts
- pages/index.tsx
closes #325 
ホームキャリア「もっと見る」の遷移先を変更
> ホームキャリア「もっと見る」の遷移先を変更

- next-env.d.ts
- pages/careers/index.tsx
> キャリアホームリンクの遷移先変更

- components/ArticleLinkEvent.tsx
> h-fullにしました
